In [ ]:
import nltk
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding,LSTM
from tensorflow.keras.optimizers import SGD
from nltk.corpus import movie_reviews
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

WARNING:tensorflow:From c:\Users\visha\anaconda3\envs\cpu_env\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [ ]:
nltk.download('movie_reviews')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\visha\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!

True

In [ ]:
import pandas as pd

data = [(movie_reviews.raw(fileid), category) for category in movie_reviews.categories() for fileid in movie_reviews.fileids(category)]

documents, labels = [data[i][0] for i in range(len(data))], [data[i][1] for i in range(len(data))]
df=pd.DataFrame()
df["review"]=documents
df["label"]=labels
df

                                                 review label
0     plot : two teen couples go to a church party ,...   neg
1     the happy bastard's quick movie review \ndamn ...   neg
2     it is movies like these that make a jaded movi...   neg
3      " quest for camelot " is warner bros . ' firs...   neg
4     synopsis : a mentally unstable man undergoing ...   neg
...                                                 ...   ...
1995  wow ! what a movie . \nit's everything a movie...   pos
1996  richard gere can be a commanding actor , but h...   pos
1997  glory--starring matthew broderick , denzel was...   pos
1998  steven spielberg's second epic film on world w...   pos
1999  truman ( " true-man " ) burbank is the perfect...   pos

[2000 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
labels = le.fit_transform(labels)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

# nltk.download('movie_reviews')
# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')

#Lower case
def lower(text):
    return text.lower()

#Punctuation remove kr
def punct_remove(text):
    new_text = re.sub(r'[^\w\s]', '', text)
    new_text = re.sub(r'https?://\S+', '',new_text)
    return new_text

def tokenize(text):
    return word_tokenize(text)

def stop_word_remove(tokens):
    stop_words = set(stopwords.words('english'))
    result = [word for word in tokens if word not in stop_words and word.isalpha()]
    return result

def stemming(tokens):
    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(word) for word in tokens]
    return stemmed_tokens

def lemmatizing(tokens):
    lemmatizer = WordNetLemmatizer()
    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return lemmatized_tokens

def preprocess_text(text):

    #lower the text
    text_lower = lower(text)

    #remove punctuation
    punct_text = punct_remove(text_lower)

    #tokenize text
    tokens = tokenize(punct_text)

     #remove stopwords
    tokens = stop_word_remove(tokens)

    stemmed_tokens = stemming(tokens)   #stemmetize

    lemmatized_tokens = lemmatizing(tokens) #lemmetize

    return " ".join(lemmatized_tokens)

demo = "This is a boy girl"
preprocess_text(demo)

'boy girl'

In [ ]:
df["review"]=df["review"].apply(preprocess_text)
df

                                                 review label
0     plot two teen couple go church party drink dri...   neg
1     happy bastard quick movie review damn bug got ...   neg
2     movie like make jaded movie viewer thankful in...   neg
3     quest camelot warner bros first featurelength ...   neg
4     synopsis mentally unstable man undergoing psyc...   neg
...                                                 ...   ...
1995  wow movie everything movie funny dramatic inte...   pos
1996  richard gere commanding actor he always great ...   pos
1997  glorystarring matthew broderick denzel washing...   pos
1998  steven spielberg second epic film world war ii...   pos
1999  truman trueman burbank perfect name jim carrey...   pos

[2000 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
documents = df["review"].values

cv=CountVectorizer() #to count unique words
cv.fit(documents)
vocab_size = len(cv.vocabulary_)
print(vocab_size)
print(cv.vocabulary_)
cv.get_feature_names_out()

41380

array(['aa', 'aaa', 'aaaaaaaaah', ..., 'zwicks', 'zwigoffs', 'zycie'],
      dtype=object)

In [ ]:
max_length = max([len(i) for i in documents])
max_length

10320

In [ ]:
vocab_size = 10000
tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(documents)

sequences = tokenizer.texts_to_sequences(documents)

max_length = 1000
X = pad_sequences(sequences, maxlen=max_length, padding='post')
print(X.shape)
print(X[0])

(2000, 1000)
[  27   18  701  214   21 1657  581 2587  835    7 1104    3   78 1164
  520 1400   16   19 1452  480  382  131    2 8380   55 1908    2  701
 1006  725  587  175  437   33 3211    9  266   10 3285    3 1088  105
 1186 7818    1  195  476 5312  732  220  252 3561 7349   11   33   17
  154  509    1 1176  150    3 5518  151  504  174 3466  962 2643 2107
  119    2   22  253  119  232 6964  136 1128  885   66   57  407  175
  480   82  391    4  425   62  291  360   41    5  291  634 9776 9011
  568    8 2993 1276   23  516  232 1744 2588   46  196  157 8381    1
   73   58 1582    7  146 3467    1  812  119  503  193   71  536 2021
   64   65 2021  223  271  450  107    9   23  341 2542   10 1583 5081
   26 1142   76 3787 3667  408    5   88 3668 1967   89  136    9   29
  139  162   63  150    9    1  341  490 1484  113    2    5  152    9
  179   57   10  190  536 1796   66 2073  248  798 6965 9012  340  127
 1277  107  367    2 1503 3286  980    7   31 2840   46   30   26  168
   16  539   48  230    8 2543 1879   82    2  547  548  716    1  127
   45   54 7819  174  717  701    2  963  490 1119 1177 1565  199  326
   29 1187   13    9  162   44  174   11   76   98 2323 9013  544  300
 1880    4  160  886   40 4427  812 4711   21 9012  535  367  245    1
   88  353    4  746    1   42 1302   42 2208 1322 1222  120  174 6307
 8382  301  174  587  215 1504  629  582   17  212  701 1485  408   41
   17  258  547 6308  409   63 1188  181   15 2994  338   18   24  580
 1333 3898  112  105  914 2400 3562 3788  425 1452 6309  573 1262 1020
 2108 2108 6310  252 3561 7349  360 3468 2734    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0]

In [ ]:
tokenizer.word_index

{'film': 1,
 'movie': 2,
 'one': 3,
 'character': 4,
 'like': 5,
 'time': 6,
 'get': 7,
 'scene': 8,
 'make': 9,
 'even': 10,
 'good': 11,
 'story': 12,
 'would': 13,
 'much': 14,
 'also': 15,
 'see': 16,
 'way': 17,
 'two': 18,
 'life': 19,
 'first': 20,
 'go': 21,
 'well': 22,
 'thing': 23,
 'year': 24,
 'take': 25,
 'really': 26,
 'plot': 27,
 'come': 28,
 'little': 29,
 'know': 30,
 'people': 31,
 'could': 32,
 'bad': 33,
 'work': 34,
 'never': 35,
 'man': 36,
 'performance': 37,
 'end': 38,
 'best': 39,
 'new': 40,
 'look': 41,
 'doesnt': 42,
 'many': 43,
 'actor': 44,
 'director': 45,
 'dont': 46,
 'play': 47,
 'u': 48,
 'love': 49,
 'action': 50,
 'he': 51,
 'role': 52,
 'great': 53,
 'show': 54,
 'find': 55,
 'another': 56,
 'audience': 57,
 'give': 58,
 'star': 59,
 'say': 60,
 'something': 61,
 'back': 62,
 'still': 63,
 'seems': 64,
 'want': 65,
 'world': 66,
 'made': 67,
 'there': 68,
 'however': 69,
 'think': 70,
 'big': 71,
 'day': 72,
 'every': 73,
 'though': 74,
 'better': 75,
 'part': 76,
 'enough': 77,
 'guy': 78,
 'seen': 79,
 'around': 80,
 'comedy': 81,
 'going': 82,
 'isnt': 83,
 'may': 84,
 'real': 85,
 'fact': 86,
 'last': 87,
 'actually': 88,
 'point': 89,
 'funny': 90,
 'right': 91,
 'lot': 92,
 'almost': 93,
 'woman': 94,
 'script': 95,
 'nothing': 96,
 'effect': 97,
 'although': 98,
 'john': 99,
 'friend': 100,
 'thats': 101,
 'played': 102,
 'set': 103,
 'cast': 104,
 'since': 105,
 'moment': 106,
 'minute': 107,
 'turn': 108,
 'long': 109,
 'old': 110,
 'young': 111,
 'ever': 112,
 'line': 113,
 'original': 114,
 'place': 115,
 'without': 116,
 'acting': 117,
 'family': 118,
 'problem': 119,
 'feel': 120,
 'try': 121,
 'least': 122,
 'picture': 123,
 'quite': 124,
 'sequence': 125,
 'girl': 126,
 'away': 127,
 'course': 128,
 'screen': 129,
 'cant': 130,
 'watch': 131,
 'three': 132,
 'interesting': 133,
 'im': 134,
 'might': 135,
 'start': 136,
 'rather': 137,
 'anything': 138,
 'bit': 139,
 'far': 140,
 'help': 141,
 'must': 142,
 'job': 143,
 'yet': 144,
 'tell': 145,
 'kind': 146,
 'alien': 147,
 'wife': 148,
 'begin': 149,
 'didnt': 150,
 'seem': 151,
 'always': 152,
 'fun': 153,
 'making': 154,
 'reason': 155,
 'special': 156,
 'trying': 157,
 'instead': 158,
 'home': 159,
 'american': 160,
 'hollywood': 161,
 'sense': 162,
 'put': 163,
 'human': 164,
 'child': 165,
 'series': 166,
 'probably': 167,
 'need': 168,
 'hour': 169,
 'along': 170,
 'war': 171,
 'becomes': 172,
 'men': 173,
 'pretty': 174,
 'idea': 175,
 'everything': 176,
 'dialogue': 177,
 'night': 178,
 'sure': 179,
 'run': 180,
 'kid': 181,
 'keep': 182,
 'black': 183,
 'together': 184,
 'shot': 185,
 'become': 186,
 'high': 187,
 'hard': 188,
 'money': 189,
 'given': 190,
 'whole': 191,
 'watching': 192,
 'got': 193,
 'let': 194,
 'attempt': 195,
 'mind': 196,
 'lead': 197,
 'death': 198,
 'music': 199,
 'hand': 200,
 'father': 201,
 'city': 202,
 'fall': 203,
 'name': 204,
 'case': 205,
 'perhaps': 206,
 'done': 207,
 'boy': 208,
 'question': 209,
 'brother': 210,
 'especially': 211,
 'horror': 212,
 'sex': 213,
 'couple': 214,
 'ending': 215,
 'less': 216,
 'next': 217,
 'relationship': 218,
 'laugh': 219,
 'head': 220,
 'everyone': 221,
 'meet': 222,
 'completely': 223,
 'rest': 224,
 'looking': 225,
 'whose': 226,
 'second': 227,
 'evil': 228,
 'feature': 229,
 'different': 230,
 'thought': 231,
 'simply': 232,
 'word': 233,
 'eye': 234,
 'james': 235,
 'mr': 236,
 'mother': 237,
 'michael': 238,
 'several': 239,
 'theyre': 240,
 'left': 241,
 'book': 242,
 'anyone': 243,
 'shes': 244,
 'entire': 245,
 'humor': 246,
 'small': 247,
 'mean': 248,
 'face': 249,
 'getting': 250,
 'group': 251,
 'lost': 252,
 'main': 253,
 'half': 254,
 'town': 255,
 'found': 256,
 'school': 257,
 'someone': 258,
 'use': 259,
 'house': 260,
 'comic': 261,
 'matter': 262,
 'joke': 263,
 'true': 264,
 'game': 265,
 'review': 266,
 'element': 267,
 'fan': 268,
 'either': 269,
 'fight': 270,
 'final': 271,
 'unfortunately': 272,
 'soon': 273,
 'later': 274,
 'ive': 275,
 'viewer': 276,
 'david': 277,
 'wrong': 278,
 'care': 279,
 'car': 280,
 'sound': 281,
 'hit': 282,
 'else': 283,
 'based': 284,
 'robert': 285,
 'written': 286,
 'camera': 287,
 'used': 288,
 'tv': 289,
 'often': 290,
 'dead': 291,
 'certainly': 292,
 'side': 293,
 'kill': 294,
 'believe': 295,
 'called': 296,
 'person': 297,
 'said': 298,
 'named': 299,
 'playing': 300,
 'despite': 301,
 'behind': 302,
 'finally': 303,
 'act': 304,
 'hero': 305,
 'maybe': 306,
 'son': 307,
 'credit': 308,
 'summer': 309,
 'able': 310,
 'power': 311,
 'past': 312,
 'nice': 313,
 'seeing': 314,
 'youre': 315,
 'perfect': 316,
 'killer': 317,
 'lack': 318,
 'example': 319,
 'including': 320,
 'classic': 321,
 'style': 322,
 'hope': 323,
 'situation': 324,
 'piece': 325,
 'video': 326,
 'order': 327,
 'theater': 328,
 'open': 329,
 'supposed': 330,
 'result': 331,
 'daughter': 332,
 'event': 333,
 'live': 334,
 'sort': 335,
 'team': 336,
 'talent': 337,
 'production': 338,
 'directed': 339,
 'running': 340,
 'entertaining': 341,
 'save': 342,
 'title': 343,
 'version': 344,
 'body': 345,
 'full': 346,
 'move': 347,
 'worth': 348,
 'change': 349,
 'call': 350,
 'drama': 351,
 'dark': 352,
 'feeling': 353,
 'worst': 354,
 'murder': 355,
 'return': 356,
 'kevin': 357,
 'top': 358,
 'upon': 359,
 'others': 360,
 'nearly': 361,
 'opening': 362,
 'thriller': 363,
 'stop': 364,
 'major': 365,
 'screenplay': 366,
 'throughout': 367,
 'direction': 368,
 'short': 369,
 'violence': 370,
 'room': 371,
 'exactly': 372,
 'scream': 373,
 'writer': 374,
 'wonder': 375,
 'earth': 376,
 'early': 377,
 'voice': 378,
 'dog': 379,
 'ship': 380,
 'beautiful': 381,
 'deal': 382,
 'wasnt': 383,
 'jack': 384,
 'white': 385,
 'who': 386,
 'heart': 387,
 'obvious': 388,
 'add': 389,
 'joe': 390,
 'dream': 391,
 'note': 392,
 'already': 393,
 'experience': 394,
 'level': 395,
 'filmmaker': 396,
 'art': 397,
 'fine': 398,
 'surprise': 399,
 'simple': 400,
 'talk': 401,
 'king': 402,
 'disney': 403,
 'novel': 404,
 'supporting': 405,
 'truly': 406,
 'member': 407,
 'flick': 408,
 'genre': 409,
 'space': 410,
 'deep': 411,
 'cop': 412,
 'number': 413,
 'tom': 414,
 'sometimes': 415,
 'boring': 416,
 'career': 417,
 'hell': 418,
 'battle': 419,
 'beginning': 420,
 'known': 421,
 'peter': 422,
 'lee': 423,
 'york': 424,
 'coming': 425,
 'wont': 426,
 'force': 427,
 'four': 428,
 'planet': 429,
 'husband': 430,
 'sequel': 431,
 'arent': 432,
 'strong': 433,
 'figure': 434,
 'plan': 435,
 'happens': 436,
 'present': 437,
 'jackie': 438,
 'state': 439,
 'saw': 440,
 'offer': 441,
 'stupid': 442,
 'possible': 443,
 'yes': 444,
 'parent': 445,
 'god': 446,
 'tale': 447,
 'quickly': 448,
 'song': 449,
 'five': 450,
 'form': 451,
 'extremely': 452,
 'manages': 453,
 'close': 454,
 'chance': 455,
 'stand': 456,
 'material': 457,
 'interest': 458,
 'villain': 459,
 'particularly': 460,
 'attention': 461,
 'romantic': 462,
 'future': 463,
 'appears': 464,
 'involving': 465,
 'worse': 466,
 'mostly': 467,
 'involved': 468,
 'eventually': 469,
 'quality': 470,
 'police': 471,
 'taking': 472,
 'paul': 473,
 'emotional': 474,
 'dr': 475,
 'break': 476,
 'cut': 477,
 'bring': 478,
 'van': 479,
 'whats': 480,
 'fiction': 481,
 'image': 482,
 'oscar': 483,
 'smith': 484,
 'none': 485,
 'wild': 486,
 'project': 487,
 'computer': 488,
 'de': 489,
 'guess': 490,
 'score': 491,
 'crime': 492,
 'success': 493,
 'living': 494,
 'release': 495,
 'george': 496,
 'gun': 497,
 'drug': 498,
 'light': 499,
 'television': 500,
 'enjoy': 501,
 'alone': 502,
 'obviously': 503,
 'taken': 504,
 'late': 505,
 'youll': 506,
 'usually': 507,
 'among': 508,
 'type': 509,
 'single': 510,
 'premise': 511,
 'actress': 512,
 'aspect': 513,
 'read': 514,
 'detail': 515,
 'happen': 516,
 'within': 517,
 'across': 518,
 'mission': 519,
 'girlfriend': 520,
 'williams': 521,
 'chris': 522,
 'history': 523,
 'forced': 524,
 'theme': 525,
 'local': 526,
 'science': 527,
 'whether': 528,
 'easy': 529,
 'wonderful': 530,
 'crew': 531,
 'expect': 532,
 'killed': 533,
 'effort': 534,
 'hold': 535,
 'secret': 536,
 'leave': 537,
 'impressive': 538,
 'giving': 539,
 'except': 540,
 'twist': 541,
 'poor': 542,
 'america': 543,
 'seemed': 544,
 'recent': 545,
 'basically': 546,
 'apparently': 547,
 'studio': 548,
 'robin': 549,
 'agent': 550,
 'serious': 551,
 'age': 552,
 'stuff': 553,
 'told': 554,
 'important': 555,
 'reality': 556,
 'million': 557,
 'mark': 558,
 'message': 559,
 'entertainment': 560,
 'working': 561,
 'somehow': 562,
 'released': 563,
 'easily': 564,
 'rock': 565,
 'happy': 566,
 'water': 567,
 'chase': 568,
 'escape': 569,
 'brings': 570,
 'batman': 571,
 'hilarious': 572,
 'street': 573,
 'difficult': 574,
 'stay': 575,
 'vampire': 576,
 'went': 577,
 'remember': 578,
 'mystery': 579,
 'ago': 580,
 'party': 581,
 'oh': 582,
 'screenwriter': 583,
 'certain': 584,
 'using': 585,
 'ben': 586,
 'cool': 587,
 'middle': 588,
 'complete': 589,
 'wouldnt': 590,
 'ill': 591,
 'william': 592,
 'due': 593,
 'presence': 594,
 'focus': 595,
 'company': 596,
 'ryan': 597,
 'turned': 598,
 'general': 599,
 'effective': 600,
 'suspense': 601,
 'motion': 602,
 'us': 603,
 'adult': 604,
 'subject': 605,
 'romance': 606,
 'popular': 607,
 'critic': 608,
 'writing': 609,
 'bill': 610,
 'business': 611,
 'anyway': 612,
 'doubt': 613,
 'surprisingly': 614,
 'personal': 615,
 'dramatic': 616,
 'country': 617,
 'decides': 618,
 'die': 619,
 'youve': 620,
 'blood': 621,
 'somewhat': 622,
 'annoying': 623,
 'ability': 624,
 'emotion': 625,
 'previous': 626,
 'similar': 627,
 'absolutely': 628,
 'came': 629,
 'choice': 630,
 'couldnt': 631,
 'pay': 632,
 'rich': 633,
 'strange': 634,
 'cinema': 635,
 'gone': 636,
 'leaf': 637,
 'trouble': 638,
 'sexual': 639,
 'fear': 640,
 'producer': 641,
 'latest': 642,
 'former': 643,
 'excellent': 644,
 'towards': 645,
 'clear': 646,
 'view': 647,
 'successful': 648,
 'bob': 649,
 'following': 650,
 'familiar': 651,
 'intelligent': 652,
 'giant': 653,
 'visual': 654,
 'amazing': 655,
 'student': 656,
 'predictable': 657,
 'beyond': 658,
 'leaving': 659,
 'red': 660,
 'jim': 661,
 'office': 662,
 'sister': 663,
 'sam': 664,
 'starring': 665,
 'nature': 666,
 'trailer': 667,
 'prison': 668,
 'la': 669,
 'smart': 670,
 'talking': 671,
 'martin': 672,
 'definitely': 673,
 'carry': 674,
 'pull': 675,
 'victim': 676,
 'powerful': 677,
 'brilliant': 678,
 'third': 679,
 'murphy': 680,
 'felt': 681,
 'clever': 682,
 'create': 683,
 'straight': 684,
 'musical': 685,
 'bunch': 686,
 'usual': 687,
 'id': 688,
 'scary': 689,
 'wedding': 690,
 'appearance': 691,
 'wish': 692,
 'learn': 693,
 'jones': 694,
 'large': 695,
 'saying': 696,
 'flaw': 697,
 'thinking': 698,
 'favorite': 699,
 'solid': 700,
 'teen': 701,
 'follows': 702,
 'law': 703,
 'rating': 704,
 'answer': 705,
 'potential': 706,
 'lie': 707,
 'seriously': 708,
 'huge': 709,
 'near': 710,
 'unlike': 711,
 'realize': 712,
 'animated': 713,
 'amount': 714,
 'approach': 715,
 'took': 716,
 'decent': 717,
 'likely': 718,
 'follow': 719,
 'rule': 720,
 'understand': 721,
 'married': 722,
 'master': 723,
 'perfectly': 724,
 'touch': 725,
 'immediately': 726,
 'happened': 727,
 'enjoyable': 728,
 'setting': 729,
 'moving': 730,
 'truman': 731,
 'mess': 732,
 'cause': 733,
 'bond': 734,
 'created': 735,
 'heard': 736,
 'scott': 737,
 'bruce': 738,
 'fails': 739,
 'sweet': 740,
 'filled': 741,
 'attack': 742,
 'stone': 743,
 'suspect': 744,
 'park': 745,
 'overall': 746,
 'inside': 747,
 'monster': 748,
 'hate': 749,
 'particular': 750,
 'merely': 751,
 'exciting': 752,
 'private': 753,
 'wanted': 754,
 'trek': 755,
 'purpose': 756,
 'carter': 757,
 'slow': 758,
 'ultimately': 759,
 'door': 760,
 'walk': 761,
 'neither': 762,
 'toy': 763,
 'truth': 764,
 'appear': 765,
 'impossible': 766,
 'blue': 767,
 'frank': 768,
 'ten': 769,
 'depth': 770,
 'brought': 771,
 'richard': 772,
 'allen': 773,
 'class': 774,
 'wood': 775,
 'r': 776,
 'society': 777,
 'waste': 778,
 'gag': 779,
 'tim': 780,
 'killing': 781,
 'otherwise': 782,
 'liked': 783,
 'political': 784,
 'various': 785,
 'wait': 786,
 'win': 787,
 'personality': 788,
 'miss': 789,
 'player': 790,
 'dumb': 791,
 'opportunity': 792,
 'issue': 793,
 'development': 794,
 'soundtrack': 795,
 'adventure': 796,
 'tone': 797,
 'showing': 798,
 'cliche': 799,
 'sight': 800,
 'steve': 801,
 'government': 802,
 'army': 803,
 'spend': 804,
 'harry': 805,
 'share': 806,
 'talented': 807,
 'detective': 808,
 'week': 809,
 'angel': 810,
 'west': 811,
 'biggest': 812,
 'slightly': 813,
 'mar': 814,
 'female': 815,
 'earlier': 816,
 'silly': 817,
 'mary': 818,
 'today': 819,
 'havent': 820,
 'creature': 821,
 'memorable': 822,
 'box': 823,
 'background': 824,
 'club': 825,
 'hank': 826,
 'max': 827,
 'month': 828,
 'english': 829,
 'totally': 830,
 'catch': 831,
 'cold': 832,
 'fast': 833,
 'tension': 834,
 'drive': 835,
 'episode': 836,
 'control': 837,
 'charm': 838,
 'leader': 839,
 'disaster': 840,
 'hill': 841,
 'ask': 842,
 'simon': 843,
 'term': 844,
 'track': 845,
 'subplot': 846,
 'eddie': 847,
 'entirely': 848,
 'grace': 849,
 'l': 850,
 'e': 851,
 'actual': 852,
 'constantly': 853,
 'soldier': 854,
 'terrible': 855,
 'british': 856,
 'gave': 857,
 'baby': 858,
 'animation': 859,
 'island': 860,
 'throw': 861,
 'air': 862,
 'nick': 863,
 'queen': 864,
 'convincing': 865,
 'officer': 866,
 'ape': 867,
 'lover': 868,
 'atmosphere': 869,
 'ride': 870,
 'sign': 871,
 'standard': 872,
 'ridiculous': 873,
 'adam': 874,
 'cinematography': 875,
 'typical': 876,
 'fire': 877,
 'spent': 878,
 'minor': 879,
 'fairly': 880,
 'doctor': 881,
 'pick': 882,
 'impact': 883,
 'list': 884,
 'fantasy': 885,
 'beauty': 886,
 'expected': 887,
 'race': 888,
 'front': 889,
 'suddenly': 890,
 'color': 891,
 'belief': 892,
 'budget': 893,
 'greatest': 894,
 'cameo': 895,
 'sit': 896,
 'willis': 897,
 'brief': 898,
 'building': 899,
 'complex': 900,
 'violent': 901,
 'amusing': 902,
 'land': 903,
 'dull': 904,
 'basic': 905,
 'seven': 906,
 'indeed': 907,
 'modern': 908,
 'steven': 909,
 'free': 910,
 'machine': 911,
 'mike': 912,
 'key': 913,
 'whatever': 914,
 'dollar': 915,
 'road': 916,
 'cinematic': 917,
 'outside': 918,
 'ii': 919,
 'meanwhile': 920,
 'subtle': 921,
 'store': 922,
 'recently': 923,
 'clearly': 924,
 'partner': 925,
 'trip': 926,
 'step': 927,
 'plenty': 928,
 'woody': 929,
 'hear': 930,
 'college': 931,
 'prof': 932,
 'bug': 933,
 'awful': 934,
 'president': 935,
 'believable': 936,
 'climax': 937,
 'cheap': 938,
 'godzilla': 939,
 'animal': 940,
 'chemistry': 941,
 'quick': 942,
 'steal': 943,
 'shown': 944,
 'conclusion': 945,
 'band': 946,
 'possibly': 947,
 'foot': 948,
 'date': 949,
 'period': 950,
 'longer': 951,
 'aside': 952,
 'highly': 953,
 'common': 954,
 'protagonist': 955,
 'storyline': 956,
 'imagine': 957,
 'scientist': 958,
 'lawyer': 959,
 'realistic': 960,
 'cameron': 961,
 'concept': 962,
 'somewhere': 963,
 'shoot': 964,
 'strike': 965,
 'slowly': 966,
 'language': 967,
 'mention': 968,
 'telling': 969,
 'six': 970,
 'provide': 971,
 'ground': 972,
 'reach': 973,
 'sean': 974,
 'scifi': 975,
 'jerry': 976,
 'delivers': 977,
 'asks': 978,
 'search': 979,
 'okay': 980,
 'cute': 981,
 'costume': 982,
 'exception': 983,
 'flat': 984,
 'device': 985,
 'casting': 986,
 'memory': 987,
 'system': 988,
 'etc': 989,
 'brown': 990,
 'cover': 991,
 'french': 992,
 'decide': 993,
 'sent': 994,
 'incredibly': 995,
 'jackson': 996,
 'intelligence': 997,
 'value': 998,
 'j': 999,
 'join': 1000,
 ...}

In [ ]:
a = ["my name is vishal"]
tokenizer.texts_to_sequences(a)

[[204]]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)
embedding_dim = 64
# X_train_oh = tf.one_hot(X_train, depth=vocab_size)
# X_test_oh = tf.one_hot(X_test, depth=vocab_size)
# X_train_oh.shape

In [ ]:
model = Sequential([
    Embedding(input_dim = vocab_size,output_dim = embedding_dim, input_length = max_length),
    SimpleRNN(128, return_sequences=False, activation='relu'),
    Dense(128, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.summary()

WARNING:tensorflow:From c:\Users\visha\anaconda3\envs\cpu_env\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 1000, 64)          640000

 simple_rnn (SimpleRNN)      (None, 128)               24704

 dense (Dense)               (None, 128)               16512

 dense_1 (Dense)             (None, 1)                 129

=================================================================
Total params: 681345 (2.60 MB)
Trainable params: 681345 (2.60 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
opt = SGD(learning_rate=0.1)
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X_train, y_train, epochs=15, batch_size=32, validation_split=0.2)

Epoch 1/15
WARNING:tensorflow:From c:\Users\visha\anaconda3\envs\cpu_env\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\visha\anaconda3\envs\cpu_env\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

40/40 [==============================] - 16s 314ms/step - loss: 0.6934 - accuracy: 0.4992 - val_loss: 0.6977 - val_accuracy: 0.4563
Epoch 2/15
14/40 [=========>....................] - ETA: 6s - loss: 0.6950 - accuracy: 0.4866

KeyboardInterrupt:

In [ ]:
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)